### PR TITLE
Diagram database

### PR DESCRIPTION
**Pull request by tafaramafemba**
### Hello

In this project we created a database based on the following image: 
clinic_diagram

This is our result:
WhatsApp Image 2022-06-07 at 7 32 43 PM

- Created a file named schema_based_on_diagram.sql where we implemented the database from the diagram.
- Joined tables from many-to-many relationships.
- Added FK indexes.

### CODE REVIEW

**Review by OLIPLICHE — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## OPTIONAL
- I suggest that you use the `drawSQL` diagram template, the same used by Microverse because you can easily draw existing table relationships like many-to-many. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jsug9** [comment]
Dear @OLIPLICHE, thank you for the advice, could you please give me more information about this template? I think I skipped that part while reading the material.

**Comment by OLIPLICHE** [comment]
> https://drawsql.app/

**Comment by jsug9** [comment]
> https://drawsql.app/

Dear @OLIPLICHE I understand the suggestion, however in this case what I wanted to demonstrate was that the original template matched the relationships of our exported diagram from DBeaver which is based on the tables that we built.

**Pull request merged**
